export const COUNTRIES = [
    { name: 'sahara', continent: 'afrika', borderingCountries: ['brasil', 'spain', 'egipto', 'etiopia', 'nigeria'] },
    { name: 'egipto', continent: 'afrika', borderingCountries: ['sahara', 'etiopia', 'madagascar', 'israel', 'polonia', 'irak'] },
    { name: 'etiopia', continent: 'afrika', borderingCountries: ['sahara', 'egipto', 'nigeria', 'angola'] },
    { name: 'nigeria', continent: 'afrika', borderingCountries: ['uruguay', 'sahara', 'etiopia', 'angola', 'mauritania', 'sudafrica'] },
    { name: 'angola', continent: 'afrika', borderingCountries: ['mauritania', 'nigeria', 'etiopia'] },
    { name: 'mauritania', continent: 'afrika', borderingCountries: ['nigeria', 'sudafrica', 'madagascar'] },
    { name: 'sudafrica', continent: 'afrika', borderingCountries: ['nigeria', 'mauritania', 'madagascar'] },
    { name: 'madagascar', continent: 'afrika', borderingCountries: ['sudafrica', 'mauritania', 'egipto'] },

    { name: 'sumatra', continent: 'oceania', borderingCountries: ['india', 'australia'] },
    { name: 'filipinas', continent: 'oceania', borderingCountries: ['vietnam', 'australia', 'tonga'] },
    { name: 'tonga', continent: 'oceania', borderingCountries: ['filipinas', 'australia', 'california'] },
    { name: 'australia', continent: 'oceania', borderingCountries: ['sumatra', 'filipinas', 'tonga', 'tasmania', 'chile'] },
    { name: 'tasmania', continent: 'oceania', borderingCountries: ['australia', 'nuevazelandia'] },
    { name: 'nuevazelandia', continent: 'oceania', borderingCountries: ['tasmania'] },

    { name: 'rusia', continent: 'asia', borderingCountries: ['siberia', 'chechenia', 'china', 'iran', 'turquia', 'ucrania'] },
    { name: 'iran', continent: 'asia', borderingCountries: ['ucrania', 'rusia', 'irak', 'turquia'] },
    { name: 'irak', continent: 'asia', borderingCountries: ['egipto', 'albania', 'israel', 'turquia', 'iran'] },
    { name: 'israel', continent: 'asia', borderingCountries: ['irak', 'egipto', 'arabia', 'turquia'] },
    { name: 'arabia', continent: 'asia', borderingCountries: ['israel'] },
    { name: 'turquia', continent: 'asia', borderingCountries: ['israel', 'irak', 'iran', 'rusia', 'china', 'india'] },
    { name: 'india', continent: 'asia', borderingCountries: ['turquia', 'sumatra', 'china', 'malasia', 'vietnam'] },
    { name: 'vietnam', continent: 'asia', borderingCountries: ['india', 'filipinas', 'malasia', 'corea'] },
    { name: 'malasia', continent: 'asia', borderingCountries: ['india', 'vietnam', 'china', 'corea'] },
    { name: 'corea', continent: 'asia', borderingCountries: ['malasia', 'vietnam', 'japon', 'kamchatka', 'china'] },
    { name: 'china', continent: 'asia', borderingCountries: ['turquia', 'india', 'malasia', 'corea', 'kamchatka', 'chukchi', 'siberia', 'chechenia', 'rusia'] },
    { name: 'japon', continent: 'asia', borderingCountries: ['corea', 'kamchatka'] },
    { name: 'kamchatka', continent: 'asia', borderingCountries: ['japon', 'china', 'chukchi', 'corea', 'alaska'] },
    { name: 'chukchi', continent: 'asia', borderingCountries: ['kamchatka', 'china', 'alaska'] },
    { name: 'siberia', continent: 'asia', borderingCountries: ['china', 'rusia', 'chechenia'] },
    { name: 'chechenia', continent: 'asia', borderingCountries: ['rusia', 'siberia', 'china'] },


    { name: 'islandia', continent: 'europe', borderingCountries: ['groenlandia', 'irlanda', 'noruega'] },
    { name: 'irlanda', continent: 'europe', borderingCountries: ['islandia', 'britain'] },
    { name: 'britain', continent: 'europe', borderingCountries: ['irlanda', 'portugal', 'germany'] },
    { name: 'portugal', continent: 'europe', borderingCountries: ['britain', 'spain'] },
    { name: 'spain', continent: 'europe', borderingCountries: ['portugal', 'sahara', 'france'] },
    { name: 'france', continent: 'europe', borderingCountries: ['spain', 'italy', 'germany'] },
    { name: 'italy', continent: 'europe', borderingCountries: ['france', 'germany', 'croatia'] },
    { name: 'germany', continent: 'europe', borderingCountries: ['france', 'italy', 'croatia', 'serbia', 'polonia', 'britain'] },
    { name: 'croatia', continent: 'europe', borderingCountries: ['italy', 'germany', 'serbia', 'polonia'] },
    { name: 'polonia', continent: 'europe', borderingCountries: ['croatia', 'serbia', 'germany', 'egipto', 'albania', 'ucrania', 'bielorrusia'] },
    { name: 'albania', continent: 'europe', borderingCountries: ['irak', 'polonia', 'iran', 'ucrania'] },
    { name: 'ucrania', continent: 'europe', borderingCountries: ['bielorrusia', 'polonia', 'albania', 'iran', 'rusia'] },
    { name: 'bielorrusia', continent: 'europe', borderingCountries: ['ucrania', 'polonia', 'finlandia'] },
    { name: 'finlandia', continent: 'europe', borderingCountries: ['bielorrusia', 'noruega'] },
    { name: 'noruega', continent: 'europe', borderingCountries: ['finlandia', 'islandia'] },
    { name: 'serbia', continent: 'europe', borderingCountries: ['polonia', 'croatia', 'germany'] },

    { name: 'alaska', continent: 'northamerica', borderingCountries: ['chokchi', 'canada', 'kamchatka'] },
    { name: 'canada', continent: 'northamerica', borderingCountries: ['alaska', 'islandvictoria', 'oregon', 'terranova'] },
    { name: 'oregon', continent: 'northamerica', borderingCountries: ['canada', 'terranova', 'chicago', 'lasvegas'] },
    { name: 'lasvegas', continent: 'northamerica', borderingCountries: ['oregon', 'chicago', 'florida', 'california'] },
    { name: 'california', continent: 'northamerica', borderingCountries: ['lasvegas', 'tonga', 'mexico', 'florida'] },
    { name: 'florida', continent: 'northamerica', borderingCountries: ['california', 'cuba', 'lasvegas', 'chicago'] },
    { name: 'chicago', continent: 'northamerica', borderingCountries: ['florida', 'lasvegas', 'oregon', 'terranova', 'newyork'] },
    { name: 'terranova', continent: 'northamerica', borderingCountries: ['canada', 'oregon', 'chicago', 'labrador'] },
    { name: 'newyork', continent: 'northamerica', borderingCountries: ['chicago', 'groenlandia'] },
    { name: 'groenlandia', continent: 'northamerica', borderingCountries: ['islandia', 'newyork', 'labrador', 'islandvictoria'] },
    { name: 'labrador', continent: 'northamerica', borderingCountries: ['terranova', 'groenlandia'] },
    { name: 'islandvictoria', continent: 'northamerica', borderingCountries: ['canada', 'groenlandia'] },

    { name: 'mexico', continent: 'centralamerica', borderingCountries: ['california', 'cuba', 'honduras'] },
    { name: 'cuba', continent: 'centralamerica', borderingCountries: ['mexico', 'florida', 'honduras', 'jamaica'] },
    { name: 'honduras', continent: 'centralamerica', borderingCountries: ['mexico', 'cuba', 'elsalvador'] },
    { name: 'elsalvador', continent: 'centralamerica', borderingCountries: ['honduras', 'nicaragua'] },
    { name: 'nicaragua', continent: 'centralamerica', borderingCountries: ['elsalvador', 'colombia', 'jamaica'] },
    { name: 'jamaica', continent: 'centralamerica', borderingCountries: ['nicaragua', 'cuba'] },

    { name: 'colombia', continent: 'southamerica', borderingCountries: ['nicaragua', 'venezuela', 'brasil', 'chile'] },
    { name: 'venezuela', continent: 'southamerica', borderingCountries: ['colombia', 'brasil'] },
    { name: 'chile', continent: 'southamerica', borderingCountries: ['colombia', 'brasil', 'bolivia', 'argentina', 'australia'] },
    { name: 'bolivia', continent: 'southamerica', borderingCountries: ['chile', 'argentina', 'paraguay', 'brasil'] },
    { name: 'argentina', continent: 'southamerica', borderingCountries: ['chile', 'bolivia', 'paraguay', 'uruguay'] },
    { name: 'uruguay', continent: 'southamerica', borderingCountries: ['argentina', 'brasil', 'nigeria'] },
    { name: 'paraguay', continent: 'southamerica', borderingCountries: ['argentina', 'uruguay', 'brasil', 'bolivia'] },
    { name: 'brasil', continent: 'southamerica', borderingCountries: ['colombia', 'venezuela', 'chile', 'bolivia', 'paraguay', 'argentina', 'uruguay', 'sahara'] },

];

