import { Goal } from '../models/goal.model';

export const GOALS: Goal[] = [
    {
        title: `Ocupar 4 países de América del Norte, 4 de Europa, 4 de
    Asia, 3 de América del Sur, 3 de América Central, 3 de África
    y 3 de Oceanía.`,
        afrika: 3,
        northamerica: 4,
        europe: 4,
        asia: 4,
        oceania: 3,
        centralamerica: 3,
        destroyPlayer: null,
        common: 0,
        southamerica: 3
    },
    {
        title: `Ocupar Europa y América del Sur.`,
        europe: 16,
        southamerica: 8,
        afrika: 0,
        asia: 0,
        centralamerica: 0,
        destroyPlayer: null,
        northamerica: 0,
        common: 0,
        oceania: 0
    },
    {
        title: `Ocupar América del Norte, Oceanía y 5 países de África.`,
        northamerica: 12,
        oceania: 6,
        afrika: 5,
        asia: 0,
        centralamerica: 0,
        destroyPlayer: null,
        common: 0,
        europe: 0,
        southamerica: 0
    },
    {
        title: `Ocupar Asia y América Central`,
        asia: 16,
        centralamerica: 6,
        afrika: 0,
        destroyPlayer: null,
        common: 0,
        europe: 0,
        northamerica: 0,
        oceania: 0,
        southamerica: 0,
    },
    {
        title: `Ocupar América del Norte, 8 países de Asia y 4 de Europa.`,
        northamerica: 12,
        asia: 8,
        europe: 4,
        afrika: 0,
        centralamerica: 0,
        destroyPlayer: null,
        common: 0,
        oceania: 0,
        southamerica: 0,
    },
    {
        title: `Ocupar Oceanía, 6 países de Asia, 6 de África y 6 de América del Norte.`,
        oceania: 6,
        asia: 6,
        afrika: 6,
        northamerica: 6,
        centralamerica: 0,
        destroyPlayer: null,
        common: 0,
        europe: 0,
        southamerica: 0
    },
    {
        title: `Ocupar América Central, 6 países de América del Sur, 6 de
        Europa y 6 de Asia.`,
        centralamerica: 6,
        southamerica: 6,
        europe: 6,
        asia: 6,
        afrika: 0,
        destroyPlayer: null,
        common: 0,
        northamerica: 0,
        oceania: 0,
    },
    {
        title: `Ocupar América del Sur, África y 8 países de Asia.`,
        southamerica: 8,
        afrika: 8,
        asia: 8,
        centralamerica: 0,
        destroyPlayer: null,
        common: 0,
        europe: 0,
        northamerica: 0,
        oceania: 0,
    },
    {
        title: `Ocupar Oceanía, África, 4 países de América Central y 4 de Asia.`,
        oceania: 6,
        afrika: 8,
        centralamerica: 4,
        asia: 4,
        destroyPlayer: null,
        common: 0,
        europe: 0,
        northamerica: 0,
        southamerica: 0,
    },
    {
        title: `Ocupar Europa, 4 países de Asia y 4 países de América del Sur.`,
        europe: 8,
        asia: 4,
        southamerica: 4,
        afrika: 0,
        centralamerica: 0,
        destroyPlayer: null,
        common: 0,
        northamerica: 0,
        oceania: 0,
    },
    {
        title: `Ocupar 35 países en cualquier lugar del mapa.`,
        europe: 0,
        afrika: 0,
        asia: 0,
        centralamerica: 0,
        common: 35,
        destroyPlayer: null,
        northamerica: 0,
        oceania: 0,
        southamerica: 0,
    },
]