import { Goal } from '../models/goal.model';

export const GOALS: Goal[] = [
    {
        title: `Ocupar 4 países de América del Norte, 4 de Europa, 4 de
    Asia, 3 de América del Sur, 3 de América Central, 3 de África
    y 3 de Oceanía.`,
        afrika: 3,
        northAmerica: 4,
        europe: 4,
        asia: 4,
        oceania: 3,
        centralAmerica: 3,
        destroyPlayer: null,
        common: 0,
        southAmerica: 3
    },
    {
        title: `Ocupar Europa y América del Sur.`,
        europe: 16,
        southAmerica: 8,
        afrika: 0,
        asia: 0,
        centralAmerica: 0,
        destroyPlayer: null,
        northAmerica: 0,
        common: 0,
        oceania: 0
    },
    {
        title: `Ocupar América del Norte, Oceanía y 5 países de África.`,
        northAmerica: 12,
        oceania: 6,
        afrika: 5,
        asia: 0,
        centralAmerica: 0,
        destroyPlayer: null,
        common: 0,
        europe: 0,
        southAmerica: 0
    },
    {
        title: `Ocupar Asia y América Central`,
        asia: 16,
        centralAmerica: 6,
        afrika: 0,
        destroyPlayer: null,
        common: 0,
        europe: 0,
        northAmerica: 0,
        oceania: 0,
        southAmerica: 0,
    },
    {
        title: `Ocupar América del Norte, 8 países de Asia y 4 de Europa.`,
        northAmerica: 12,
        asia: 8,
        europe: 4,
        afrika: 0,
        centralAmerica: 0,
        destroyPlayer: null,
        common: 0,
        oceania: 0,
        southAmerica: 0,
    },
    {
        title: `Ocupar Oceanía, 6 países de Asia, 6 de África y 6 de América del Norte.`,
        oceania: 6,
        asia: 6,
        afrika: 6,
        northAmerica: 6,
        centralAmerica: 0,
        destroyPlayer: null,
        common: 0,
        europe: 0,
        southAmerica: 0
    },
    {
        title: `Ocupar América Central, 6 países de América del Sur, 6 de
        Europa y 6 de Asia.`,
        centralAmerica: 6,
        southAmerica: 6,
        europe: 6,
        asia: 6,
        afrika: 0,
        destroyPlayer: null,
        common: 0,
        northAmerica: 0,
        oceania: 0,
    },
    {
        title: `Ocupar América del Sur, África y 8 países de Asia.`,
        southAmerica: 8,
        afrika: 8,
        asia: 8,
        centralAmerica: 0,
        destroyPlayer: null,
        common: 0,
        europe: 0,
        northAmerica: 0,
        oceania: 0,
    },
    {
        title: `Ocupar Oceanía, África, 4 países de América Central y 4 de Asia.`,
        oceania: 6,
        afrika: 8,
        centralAmerica: 4,
        asia: 4,
        destroyPlayer: null,
        common: 0,
        europe: 0,
        northAmerica: 0,
        southAmerica: 0,
    },
    {
        title: `Ocupar Europa, 4 países de Asia y 4 países de América del Sur.`,
        europe: 8,
        asia: 4,
        southAmerica: 4,
        afrika: 0,
        centralAmerica: 0,
        destroyPlayer: null,
        common: 0,
        northAmerica: 0,
        oceania: 0,
    },
    {
        title: `Ocupar 35 países en cualquier lugar del mapa.`,
        europe: 0,
        afrika: 0,
        asia: 0,
        centralAmerica: 0,
        common: 35,
        destroyPlayer: null,
        northAmerica: 0,
        oceania: 0,
        southAmerica: 0,
    },
]